name: ChannelService

on:
  push:
    branches: [ main ]

jobs:

  pep8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install test libs
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort

#      - name: Test with isort
#        run: |
#          python -m isort backend/. --profile black
#          name: Test with isort

      - name: Test with flake8
        run: |
          python -m flake8 backend/ --max-line-length=120 --ignore=I001 --ignore=I005"
          name: Test with flake8

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

  send_message:
    runs-on: ubuntu-latest
    needs: pep8
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
